### ISSUE TITLE
Moodle 2.3 requires "intro", "introformat" columns in recordingsbn table

### ISSUE THREAD

**Issue by mrclay** [blindsidenetworks/moodle-mod_recordingsbn#11]
It looks like Moodle normalized the schema of a bunch of different resources, including adding "intro" and "introformat" columns, described a bit [here](http://docs.moodle.org/dev/Text_formats_2.0).

We didn't notice the bug until [course/resources.php](https://github.com/moodle/moodle/blob/MOODLE_23_STABLE/course/resources.php#L90) was hit on a course with recordingsbn. On line 90 it tries to SELECT the missing "intro" column.

**Comment by jfederico** [comment]
It was fixed a while back
